name: Python Application Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        python -m pip install pytest-cov

    - name: 3. Run Testing
      run: python -m pytest --cov .